from hyperopt import hp

xgboost_config_feature_list = [
  # Categorical features:
  'activation_weekday',
  'category_name',
  'city',
  'image_top_1',
  'param_1',
  'param_2',
  'param_3',
  'parent_category_name',
  'region',
  'user_type',
  'item_seq_number_bucket',
  "has_description",
  "has_image",
  "has_one_param",
  "has_price",
  "item_seq_number_is_one",
  'log_price',
  'price',
  'user_id-counts',
  'param_1-price-norm',
  'region+city+parent_category_name-counts',
  'region+category_name+param_1-price-norm',
  'item_seq_number',
  'user_id+param_1-price-mean',
  'region+param_1+activation_date-price-norm',
  'user_id+category_name-price-mean',
  'user_id+category_name-counts',
  'category_name-price-norm',
  'region+param_1-price-norm',
  'user_id+parent_category_name-counts',
  'desc_len_norm',
  'param_1+activation_date-price-norm',
  'region+city+param_1-price-norm',
  'user_id+region-counts',
  'parent_category_name-price-norm',
  'region+parent_category_name+param_1-price-norm',
  'region+city+param_1-counts',
  'user_id+parent_category_name-price-mean',
  'region+city+category_name-counts',
  'title_len_wc_ratio',
  'desc_uniq_wc',
  'title_len',
  'user_id+parent_category_name-price-std',
  'user_type-price-norm',
  'parent_category_name+param_1-price-norm',
  'category_name+param_1-price-norm',
  'user_id+param_1-price-std',
  'parent_category_name+param_1+activation_date-price-norm',
  'category_name+param_1+activation_date-price-norm',
  'desc_punc_count',
  'category_name+user_type-price-norm',
  'region+city+user_type-counts',
  'parent_category_name+activation_date-counts',
  'user_id-price-std',
  'region+parent_category_name-counts',
  'user_id+activation_date-counts',
  'user_id+activation_date-price-mean',
  'param_1-price-std',
  'user_id-price-norm',
  'region+city+category_name-price-norm',
  'desc_wc_norm',
  'user_id+param_1-counts',
  'region+param_1+user_type-price-norm',
  'region+category_name-price-norm',
  'user_id+category_name-price-std',
  'region+category_name+activation_date-price-norm',
  'region+city+activation_date-counts',
  # 'category_name-price-mean',
  'user_id-price-mean',
  'param_1+activation_date+user_type-price-norm',
  'region+city-counts',
  'category_name+activation_date-price-norm',
  'region+city+param_2-price-norm',
  'region+category_name-counts',
  'user_id+activation_date-price-std',
  'parent_category_name+user_type-price-norm',
  'parent_category_name+param_1+user_type-price-norm',
  'user_id+region-price-std',
  'region+city+param_3-price-norm',
  'desc_wc',
  'category_name-price-std',
  'category_name+param_1-price-std',
  'user_id+activation_date-price-norm',
  'region+city+parent_category_name-price-norm',
  'desc_upper_count_ratio',
  'region+category_name+user_type-price-norm',
  'region+parent_category_name-price-norm',
  'category_name+param_1+user_type-price-norm',
  'param_1-price-mean',
  'parent_category_name+param_1-price-std',
  'user_id+region-price-norm',
  'param_1+user_type-price-norm',
  'parent_category_name+activation_date+user_type-counts',
  'user_id+category_name-price-norm',
  'region+city+parent_category_name-price-mean',
  'category_name+param_1+user_type-price-std',
  'desc_letter_punc_ratio',
  'desc_uniq_wc_ratio',
  'region+param_1-counts',
  'region+city+param_2-counts',
  # 'parent_category_name-price-std',
  'user_id+param_2-price-mean',
  'region+city-price-norm',
  'user_id+region-price-mean',
  'category_name+activation_date+user_type-price-norm',
  'region+parent_category_name+activation_date-counts',
  'region+category_name-price-mean',
  'region+city+parent_category_name-price-std',
  'region+city+activation_date-price-norm',
  'region+category_name+param_1-price-mean',
  'desc_len_wc_norm_ratio',
  'desc_upper_count',
  'param_1-counts',
  'category_name+activation_date-counts',
  'param_1+user_type-counts',
  'region+activation_date+user_type-counts',
  'region+city-price-std',
  'region+parent_category_name+activation_date-price-norm',
  'region+parent_category_name+param_1-price-mean',
  'region+category_name+param_1-price-std',
  'desc_wc_norm_ratio',
  'title_wc',
  'region+parent_category_name+user_type-counts',
  'region+parent_category_name-price-std',
  'region+category_name-price-std',
  'category_name+activation_date-price-std',
  'parent_category_name+user_type-price-std',
  'region+param_2+activation_date-price-norm',
  'region+param_3+user_type-price-norm',
  # 'region+param_3+activation_date-price-norm',
  # 'desc_num_count',
  'title_num_count_ratio',
  'title_uniq_wc',
  'param_1+activation_date-price-std',
  'category_name+user_type-price-mean',
  'region+parent_category_name+param_1-price-std',
  'parent_category_name+param_1+user_type-price-std',
  'title_upper_count',
  # 'category_name-counts',
  'activation_date+user_type-counts',
  'category_name+user_type-counts',
  'param_2-price-norm',
  'region-price-norm',
  'user_id+parent_category_name-price-norm',
  'param_1+user_type-price-mean',
  'category_name+user_type-price-std',
  'region+city+user_type-price-mean',
  'region+city+user_type-price-norm',
  'region+city+param_1-price-mean',
  'region+city+param_2-price-std',
  'parent_category_name+param_1+activation_date-price-std',
  'region+city+category_name-price-std',
  'region+parent_category_name+param_1-counts',
  'region+parent_category_name-price-mean',
  'category_name+param_1-price-mean',
  # 'param_2+user_type-price-norm',
  'region+activation_date-price-std',
  # 'region+city+param_2-price-mean',
  'desc_wc_punc_ratio',
  'param_2-price-std',
  'user_id+param_1-price-norm',
  'parent_category_name+param_1-price-mean',
  'region+category_name+param_2-price-norm',
  'region+parent_category_name+user_type-price-mean',
  'region+parent_category_name+user_type-price-std',
  'category_name+param_1+activation_date-price-mean',
  'embedding',
  'avg_days_up_user',
  'avg_times_up_user',
  'n_user_items',
  # 'income2018',
  # 'growth_rate',
  "activation_date+user_type-price-diff",
    "activation_date-price-diff",
    "category_name+activation_date+user_type-price-diff",
    "category_name+activation_date-price-diff",
    "category_name+param_1+activation_date-price-diff",
    "category_name+param_1+user_type-price-diff",
    "category_name+param_1-price-diff",
    # "category_name+param_2+activation_date-price-diff",
    # "category_name+param_2+user_type-price-diff",
    "category_name+param_2-price-diff",
    # "category_name+param_3+activation_date-price-diff",
    # "category_name+param_3+user_type-price-diff",
    # "category_name+param_3-price-diff",
    "category_name+user_type-price-diff",
    "category_name-price-diff",
    "param_1+activation_date+user_type-price-diff",
    "param_1+activation_date-price-diff",
    "param_1+user_type-price-diff",
    "param_1-price-diff",
    # "param_2+activation_date+user_type-price-diff",
    # "param_2+activation_date-price-diff",
    "param_2+user_type-price-diff",
    # "param_2-price-diff",
    # "param_3+activation_date+user_type-price-diff",
    # "param_3+activation_date-price-diff",
    # "param_3+user_type-price-diff",
    # "param_3-price-diff",
    "parent_category_name+activation_date+user_type-price-diff",
    "parent_category_name+activation_date-price-diff",
    "parent_category_name+param_1+activation_date-price-diff",
    "parent_category_name+param_1+user_type-price-diff",
    "parent_category_name+param_1-price-diff",
    # "parent_category_name+param_2+activation_date-price-diff",
    # "parent_category_name+param_2+user_type-price-diff",
    # "parent_category_name+param_2-price-diff",
    # "parent_category_name+param_3+activation_date-price-diff",
    # "parent_category_name+param_3+user_type-price-diff",
    # "parent_category_name+param_3-price-diff",
    "parent_category_name+user_type-price-diff",
    "parent_category_name-price-diff",
    "region+activation_date+user_type-price-diff",
    "region+activation_date-price-diff",
    "region+category_name+activation_date-price-diff",
    "region+category_name+param_1-price-diff",
    # "region+category_name+param_2-price-diff",
    # "region+category_name+param_3-price-diff",
    "region+category_name+user_type-price-diff",
    "region+category_name-price-diff",
    "region+city+activation_date-price-diff",
    "region+city+category_name-price-diff",
    "region+city+param_1-price-diff",
    # "region+city+param_2-price-diff",
    # "region+city+param_3-price-diff",
    "region+city+parent_category_name-price-diff",
    "region+city+user_type-price-diff",
    "region+city-price-diff",
    "region+param_1+activation_date-price-diff",
    "region+param_1+user_type-price-diff",
    # "region+param_1-price-diff",
    # "region+param_2+activation_date-price-diff",
    # "region+param_2+user_type-price-diff",
    # "region+param_2-price-diff",
    # "region+param_3+activation_date-price-diff",
    # "region+param_3+user_type-price-diff",
    # "region+param_3-price-diff",
    "region+parent_category_name+activation_date-price-diff",
    # "region+parent_category_name+param_1-price-diff",
    # "region+parent_category_name+param_2-price-diff",
    # "region+parent_category_name+param_3-price-diff",
    # "region+parent_category_name+user_type-price-diff",
    "region+parent_category_name-price-diff",
    # "region+user_type-price-diff",
    # "region-price-diff",
    # "user_id+activation_date-price-diff",
    # "user_id+category_name-price-diff",
    # "user_id+param_1-price-diff",
    # "user_id+param_2-price-diff",
    # "user_id+param_3-price-diff",
    # "user_id+parent_category_name-price-diff",
    # "user_id+region-price-diff",
    # "user_id-price-diff",
    "user_type-price-diff"
]
xgboost_config = {
    'features': xgboost_config_feature_list,
    'image_feature_folders': ['ads_image_features'],
    'folds':5,
    'model': 'xgboost',
    'model_params': {
      'alpha': 0.6,
      'colsample_bylevel': 0.3,
      'colsample_bytree': 0.3,
      'eta': 0.07901772316032044,
      'eval_metric': 'rmse',
      'gamma': 0.0018188912716341973,
      'lambda': 0.4,
      'max_depth': 3,
      'min_child_weight': 4.4156043204121,
      'objective': 'reg:linear',
      'silent': 1,
      'subsample': 0.3
    },
    'tune_params': {
        'param_space': {
            'features': xgboost_config_feature_list,
            'image_feature_folders': ['image_features/ads_image_features'],
            'model': 'xgboost',
            'folds': 3,
            'model_params': {
                'eta': hp.loguniform('eta', -2, 0),
                'gamma': hp.loguniform('gamma', -4, -1),
                'max_depth': hp.choice('max_depth', [5, 7, 10]),
                'min_child_weight': hp.loguniform('min_child_weight', -3, 1),
                'subsample': hp.choice('subsample', [0.1, 0.3, 0.5, 0.7, 1]),
                'colsample_bytree': hp.choice('colsample_bytree', [0.1, 0.3]),
                'colsample_bylevel': hp.choice('colsample_bylevel', [0.3, 0.5, 0.7]),
                'lambda': hp.choice('lambda', [x/10 for x in range(0, 6)]),
                'alpha': hp.choice('alpha', [x/10 for x in range(3, 8)]),
                'objective': hp.choice('objective', ['reg:linear', 'reg:logistic']),
                'eval_metric': 'rmse',
                # 'base_score': y_mean,
                # 'booster': 'gblinear',
                'silent': 1
            },
        },
        'max_evals': 2
    }
}
